In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
b=np.array([[1,2],[3,4]])

In [7]:
b

array([[1, 2],
       [3, 4]])

In [8]:
print(b.shape)

(2, 2)


In [9]:
b[0][1]

2

In [10]:
b[1][0]

3

In [11]:
c=np.zeros(3)

In [12]:
c


array([0., 0., 0.])

In [13]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [61]:
d=np.array(range(3))

In [62]:
d

array([0, 1, 2])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
e=np.random.random((2,3))

In [18]:
e

array([[0.9292663 , 0.86226344, 0.57237075],
       [0.2161816 , 0.86745301, 0.66610735]])

In [19]:
print(e[1,:])

[0.2161816  0.86745301 0.66610735]


In [20]:
e[1,1:]

array([0.86745301, 0.66610735])

In [21]:
z=np.zeros((3,3))

In [22]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
z[1:,1:]=1

In [24]:
z


array([[0., 0., 0.],
       [0., 1., 1.],
       [0., 1., 1.]])

In [25]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.array([[9,10],[11,12]])
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [26]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [27]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [28]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [29]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [30]:
print(x.dot(y.dot(z)))

[[ 413  454]
 [ 937 1030]]


In [31]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [32]:
a=np.array([1,2,3,4])

In [33]:
print(np.dot(a,a))

30


In [34]:
print(sum(a))

10


In [35]:
np.sum(a)

10

In [36]:
np.sum(x,axis=1)

array([3, 7])

In [37]:
np.sum(x,axis=0)

array([4, 6])

In [38]:
b=a**2

In [39]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [40]:
e=np.array(range(8))

In [41]:
e.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [42]:
a=np.arange(10)

In [43]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
a=np.arange(10)+5

In [46]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
import numpy as np
np.random.seed(1)
np.random.shuffle(a)
print(a)

[6 8 7]


In [53]:
a=np.random.randn(2,3)
print(a)

[[-1.61830503 -0.39454356 -0.62089558]
 [ 0.3468652  -0.5876713  -1.63018935]]


In [55]:
a=np.random.randint(5,10,3)

In [56]:
a

array([6, 7, 8])

In [57]:
element=np.random.choice(np.arange(10))

In [60]:
element

2

In [67]:
a=np.array([np.arange(5),np.arange(5)+5])
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
print(np.min(a))

0


In [69]:
print(np.sum(a))

45


In [70]:
print(np.max(a))

9


In [74]:
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

4.5
[2.5 3.5 4.5 5.5 6.5]
[2. 7.]


In [76]:
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))

4.5
[2.5 3.5 4.5 5.5 6.5]
[2. 7.]


In [77]:
np.std(a)

2.8722813232690143

In [78]:
np.var(a)

8.25